package com.besson.endfield.datagen;

import com.besson.endfield.block.ModBlocks;
import com.besson.endfield.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;

public class ModEnUsLangProvider extends FabricLanguageProvider {
    public ModEnUsLangProvider(FabricDataOutput dataOutput) {
        super(dataOutput, "en_us");
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add(ModItems.PROTOCOL_ANCHOR_CORE_ITEM, "Protocol Anchor Core");
        translationBuilder.add(ModItems.RELAY_TOWER_ITEM, "Relay Tower");
        translationBuilder.add(ModItems.ELECTRIC_PYLON_ITEM, "Electric Pylon");
        translationBuilder.add(ModItems.ELECTRIC_MINING_RIG_ITEM, "Electric Mining Rig");
        translationBuilder.add(ModItems.ELECTRIC_MINING_RIG_MK_II_ITEM, "Electric Mining Rig Mk II");
        translationBuilder.add(ModItems.PORTABLE_ORIGINIUM_RIG_ITEM, "Portable Originium Rig");
        translationBuilder.add(ModItems.REFINING_UNIT_ITEM, "Refining Unit");
        translationBuilder.add(ModItems.SHREDDING_UNIT_ITEM, "Shredding Unit");
        translationBuilder.add(ModItems.FILLING_UNIT_ITEM, "Filling Unit");
        translationBuilder.add(ModItems.FITTING_UNIT_ITEM, "Fitting Unit");
        translationBuilder.add(ModItems.GEARING_UNIT_ITEM, "Gearing Unit");
        translationBuilder.add(ModItems.GRINDING_UNIT_ITEM, "Grinding Unit");
        translationBuilder.add(ModItems.MOULDING_UNIT_ITEM, "Moulding Unit");
        translationBuilder.add(ModItems.PACKAGING_UNIT_ITEM, "Packaging Unit");
        translationBuilder.add(ModItems.PLANTING_UNIT_ITEM, "Planting Unit");
        translationBuilder.add(ModItems.SEED_PICKING_UNIT_ITEM, "Seed-Picking Unit");
        translationBuilder.add(ModItems.THERMAL_BANK_ITEM, "Thermal Unit");

        translationBuilder.add(ModBlocks.AMETHYST_MINERAL_VEIN_BLOCK, "Amethyst Mineral Vein");
        translationBuilder.add(ModBlocks.COAL_MINERAL_VEIN_BLOCK, "Coal Mineral Vein");
        translationBuilder.add(ModBlocks.COPPER_MINERAL_VEIN_BLOCK, "Copper Mineral Vein");
        translationBuilder.add(ModBlocks.DIAMOND_MINERAL_VEIN_BLOCK, "Diamond Mineral Vein");
        translationBuilder.add(ModBlocks.EMERALD_MINERAL_VEIN_BLOCK, "Emerald Mineral Vein");
        translationBuilder.add(ModBlocks.GOLD_MINERAL_VEIN_BLOCK, "Gold Mineral Vein");
        translationBuilder.add(ModBlocks.IRON_MINERAL_VEIN_BLOCK, "Iron Mineral Vein");
        translationBuilder.add(ModBlocks.LAPIS_MINERAL_VEIN_BLOCK, "Lapis Mineral Vein");
        translationBuilder.add(ModBlocks.ORIGINIUM_MINERAL_VEIN_BLOCK, "Originium Mineral Vein");
        translationBuilder.add(ModBlocks.REDSTONE_MINERAL_VEIN_BLOCK, "Redstone Mineral Vein");
        translationBuilder.add(ModBlocks.AMETHYST_ORE_BLOCK, "Amethyst Ore");
        translationBuilder.add(ModBlocks.CUPRIUM_MINERAL_VEIN_BLOCK, "Cuprium Mineral Vein");
        translationBuilder.add(ModBlocks.CUPRIUM_ORE_BLOCK, "Cuprium Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_AMETHYST_ORE, "Deepslate Amethyst Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_CUPRIUM_ORE, "Deepslate Cuprium Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_FERRIUM_ORE, "Deepslate Ferrium Ore");
        translationBuilder.add(ModBlocks.DEEPSLATE_ORIGINIUM_ORE, "Deepslate Originium Ore");
        translationBuilder.add(ModBlocks.FERRIUM_MINERAL_VEIN_BLOCK, "Ferrium Mineral Vein");
        translationBuilder.add(ModBlocks.FERRIUM_ORE_BLOCK, "Ferrium Ore");
        translationBuilder.add(ModBlocks.ORIGINIUM_ORE_BLOCK, "Originium Ore");

        translationBuilder.add(ModBlocks.CRAFTER, "Crafter");

        translationBuilder.add(ModItems.AGGAGRIT, "Aggagrit");
        translationBuilder.add(ModItems.AGGAGRIT_BLOCK, "Aggagrit Block");
        translationBuilder.add(ModItems.AGGAGRIT_CLUSTER, "Aggagrit Cluster");
        translationBuilder.add(ModItems.AKETINE, "Aketine");
        translationBuilder.add("item.arknights_endfield.aketine", "Aketine");
        translationBuilder.add(ModItems.AKETINE_POWDER, "Aketine Powder");
        translationBuilder.add(ModItems.AKETINE_SEED, "Aketine Seed");
        translationBuilder.add(ModItems.AMBER_RICE, "Amber Rice");
        translationBuilder.add("item.arknights_endfield.amber_rice", "Amber Rice");
        translationBuilder.add(ModItems.AMBER_RICE_SEED, "Amber Rice Seed");
        translationBuilder.add(ModItems.AMETHYST_BOTTLE, "Amethyst Bottle");
        translationBuilder.add(ModItems.AMETHYST_COMPONENT, "Amethyst Component");
        translationBuilder.add(ModItems.AMETHYST_FIBER, "Amethyst Fiber");
        translationBuilder.add(ModItems.AMETHYST_ORE, "Amethyst Ore");
        translationBuilder.add(ModItems.AMETHYST_PART, "Amethyst Part");
        translationBuilder.add(ModItems.AMETHYST_POWDER, "Amethyst Powder");
        translationBuilder.add(ModItems.ARTS_TUBE, "Arts Tube");
        translationBuilder.add(ModItems.ARTS_VIAL, "Arts Vial");
        translationBuilder.add(ModItems.ASHPIN_REMEDY, "Ashpin Remedy");
        translationBuilder.add(ModItems.BIZARROTACK, "Bizarrotack");
        translationBuilder.add(ModItems.BIZARRO_CHILI, "Bizarro Chili");
        translationBuilder.add(ModItems.BLANCHED_REMEDY, "Blanched Remedy");
        translationBuilder.add(ModItems.BUCKFLOWER, "Buckflower");
        translationBuilder.add("item.arknights_endfield.buckflower", "Buckflower");
        translationBuilder.add(ModItems.BUCKFLOWER_POWDER, "Buckflower Powder");
        translationBuilder.add(ModItems.BUCKFLOWER_SEED, "Buckflower Seed");
        translationBuilder.add(ModItems.BUCKPILL_L, "Buckpill L");
        translationBuilder.add(ModItems.BUCKPILL_RF, "Buckpill Rf");
        translationBuilder.add(ModItems.BUCKPILL_S, "Buckpill S");
        translationBuilder.add(ModItems.BUCK_CAPSULE_A, "Buck Capsule A");
        translationBuilder.add(ModItems.BUCK_CAPSULE_B, "Buck Capsule B");
        translationBuilder.add(ModItems.BUCK_CAPSULE_C, "Buck Capsule C");
        translationBuilder.add(ModItems.BUGTACK, "Bugtack");
        translationBuilder.add(ModItems.CANNED_CITROME_A, "Canned Citrome A");
        translationBuilder.add(ModItems.CANNED_CITROME_B, "Canned Citrome B");
        translationBuilder.add(ModItems.CANNED_CITROME_C, "Canned Citrome C");
        translationBuilder.add(ModItems.CARBON, "Carbon");
        translationBuilder.add(ModItems.CARBON_POWDER, "Carbon Powder");
        translationBuilder.add(ModItems.CARTILAGE_BIT, "Cartilage Bit");
        translationBuilder.add(ModItems.CARTILAGE_TACK, "Cartilage Tack");
        translationBuilder.add(ModItems.CHITIN_BIT, "Chitin Bit");
        translationBuilder.add(ModItems.CITROBUCKY_MIX, "Citrobucky Mix");
        translationBuilder.add(ModItems.CITROME, "Citrome");
        translationBuilder.add("item.arknights_endfield.citrome", "Citrome");
        translationBuilder.add(ModItems.CITROME_JAM, "Citrome Jam");
        translationBuilder.add(ModItems.CITROME_JELLY, "Citrome Jelly");
        translationBuilder.add(ModItems.CITROME_POWDER, "Citrome Powder");
        translationBuilder.add(ModItems.CITROME_PUDDING, "Citrome Pudding");
        translationBuilder.add(ModItems.CITROME_SEED, "Citrome Seed");
        translationBuilder.add(ModItems.CITROMIX, "Citromix");
        translationBuilder.add(ModItems.CITROMIX_L, "Citromix L");
        translationBuilder.add(ModItems.CITROMIX_RF, "Citromix Rf");
        translationBuilder.add(ModItems.CITROMIX_S, "Citromix S");
        translationBuilder.add(ModItems.COARSE_FLATBREAD, "Coarse Flatbread");
        translationBuilder.add(ModItems.CORRECTIVE_REMEDY, "Corrective Remedy");
        translationBuilder.add(ModItems.CRYSTON_BOTTLE, "Cryston Bottle");
        translationBuilder.add(ModItems.CRYSTON_COMPONENT, "Cryston Component");
        translationBuilder.add(ModItems.CRYSTON_FIBER, "Cryston Fiber");
        translationBuilder.add(ModItems.CRYSTON_PART, "Cryston Part");
        translationBuilder.add(ModItems.CRYSTON_POWDER, "Cryston Powder");
        translationBuilder.add(ModItems.CUPRIUM, "Cuprium");
        translationBuilder.add(ModItems.CUPRIUM_COMPONENT, "Cuprium Component");
        translationBuilder.add(ModItems.CUPRIUM_JAR, "Cuprium Jar");
        translationBuilder.add(ModItems.CUPRIUM_ORE, "Cuprium Ore");
        translationBuilder.add(ModItems.CUPRIUM_PART, "Cuprium Part");
        translationBuilder.add(ModItems.CUPRIUM_POWDER, "Cuprium Powder");
        translationBuilder.add(ModItems.DENSE_CARBON_POWDER, "Dense Carbon Powder");
        translationBuilder.add(ModItems.DENSE_FERRIUM_POWDER, "Dense Ferrium Powder");
        translationBuilder.add(ModItems.DENSE_ORIGINIUM_POWDER, "Dense Originium Powder");
        translationBuilder.add(ModItems.DENSE_ORIGOCRUST_POWDER, "Dense Origocrust Powder");
        translationBuilder.add(ModItems.FERRIUM, "Ferrium");
        translationBuilder.add(ModItems.FERRIUM_BOTTLE, "Ferrium Bottle");
        translationBuilder.add(ModItems.FERRIUM_COMPONENT, "Ferrium Component");
        translationBuilder.add(ModItems.FERRIUM_ORE, "Ferrium Ore");
        translationBuilder.add(ModItems.FERRIUM_PART, "Ferrium Part");
        translationBuilder.add(ModItems.FERRIUM_POWDER, "Ferrium Powder");
        translationBuilder.add(ModItems.FILLET, "Fillet");
        translationBuilder.add(ModItems.FILLET_CONFIT, "Fillet Confit");
        translationBuilder.add(ModItems.FIREBUCKLE, "Firebuckle");
        translationBuilder.add("item.arknights_endfield.firebuckle", "Firebuckle");
        translationBuilder.add(ModItems.FIREBUCKLE_POWDER, "Firebuckle Powder");
        translationBuilder.add(ModItems.FIRESTOVE_RICE, "Firestove Rice");
        translationBuilder.add(ModItems.FIRETACK, "Firetack");
        translationBuilder.add(ModItems.FLUFFED_JINCAO, "Fluffed Jincao");
        translationBuilder.add("item.arknights_endfield.fluffed_jincao", "Fluffed Jincao");
        translationBuilder.add(ModItems.FLUFFED_JINCAO_POWDER, "Fluffed Jincao Powder");
        translationBuilder.add(ModItems.FORTIFYING_INFUSION, "Fortifying Infusion");
        translationBuilder.add(ModItems.GARDEN_FRIED_RICE, "Garden Fried Rice");
        translationBuilder.add(ModItems.GARDEN_STIR_FRY, "Garden Stir Fry");
        translationBuilder.add(ModItems.GINSENG_MEAT_STEW, "Ginseng Meat Stew");
        translationBuilder.add(ModItems.GLOWBUG, "Glowbug");
        translationBuilder.add(ModItems.GRASS_CHAFF, "Grass Chaff");
        translationBuilder.add(ModItems.GROUND_BUCKFLOWER_POWDER, "Ground Buckflower Powder");
        translationBuilder.add(ModItems.GROUND_CITROME_POWDER, "Ground Citrome Powder");
        translationBuilder.add(ModItems.HC_BATTERY, "Hc Battery");
        translationBuilder.add(ModItems.HOLLOW_BONE, "Hollow Bone");
        translationBuilder.add(ModItems.HOLLOW_BONECHIP, "Hollow Bonechip");
        translationBuilder.add(ModItems.HOT_CRUNCHY_RIBS, "Hot Crunchy Ribs");
        translationBuilder.add(ModItems.INDUSTRIAL_EXPLOSIVE, "Industrial Explosive");
        translationBuilder.add(ModItems.JINCAO, "Jincao");
        translationBuilder.add("item.arknights_endfield.jincao", "Jincao");
        translationBuilder.add(ModItems.JINCAO_DRINK, "Jincao Drink");
        translationBuilder.add(ModItems.JINCAO_INFUSION, "Jincao Infusion");
        translationBuilder.add(ModItems.JINCAO_POWDER, "Jincao Powder");
        translationBuilder.add(ModItems.JINCAO_SEED, "Jincao Seed");
        translationBuilder.add(ModItems.JINCAO_TEA, "Jincao Tea");
        translationBuilder.add(ModItems.JINCAO_TISANE, "Jincao Tisane");
        translationBuilder.add(ModItems.KUNST_TUBE, "Kunst Tube");
        translationBuilder.add(ModItems.KUNST_VIAL, "Kunst Vial");
        translationBuilder.add(ModItems.LC_BATTERY, "Lc Battery");
        translationBuilder.add(ModItems.MEAT_STIR_FRY, "Meat Stir Fry");
        translationBuilder.add(ModItems.MOSSFIELD_PIE, "Mossfield Pie");
        translationBuilder.add(ModItems.ORIGINIUM_ORE, "Originium Ore");
        translationBuilder.add(ModItems.ORIGINIUM_POWDER, "Originium Powder");
        translationBuilder.add(ModItems.ORIGOCRUST, "Origocrust");
        translationBuilder.add(ModItems.ORIGOCRUST_POWDER, "Origocrust Powder");
        translationBuilder.add(ModItems.PACKED_ORIGOCRUST, "Packed Origocrust");
        translationBuilder.add(ModItems.PERPLEXING_MEDICATION, "Perplexing Medication");
        translationBuilder.add(ModItems.PRESERVE_STEW, "Preserve Stew");
        translationBuilder.add(ModItems.REDJADE_GINSENG, "Redjade Ginseng");
        translationBuilder.add("item.arknights_endfield.redjade_ginseng", "Redjade Ginseng");
        translationBuilder.add(ModItems.REDJADE_GINSENG_SEED, "Redjade Ginseng Seed");
        translationBuilder.add(ModItems.REED_RYE, "Reed Rye");
        translationBuilder.add("item.arknights_endfield.reed_rye", "Reed Rye");
        translationBuilder.add(ModItems.REED_RYE_SEED, "Reed Rye Seed");
        translationBuilder.add(ModItems.SANDLEAF, "Sandleaf");
        translationBuilder.add("item.arknights_endfield.sandleaf", "Sandleaf");
        translationBuilder.add(ModItems.SANDLEAF_POWDER, "Sandleaf Powder");
        translationBuilder.add(ModItems.SANDLEAF_SEED, "Sandleaf Seed");
        translationBuilder.add(ModItems.SAVORY_FILLET, "Savory Fillet");
        translationBuilder.add(ModItems.SAVORY_TANGBAO, "Savory Tangbao");
        translationBuilder.add(ModItems.SAVORY_TANGMIAN, "Savory Tangmian");
        translationBuilder.add(ModItems.SCORCHBUG, "Scorchbug");
        translationBuilder.add(ModItems.SC_BATTERY, "Sc Battery");
        translationBuilder.add(ModItems.SENSORY_REMEDY, "Sensory Remedy");
        translationBuilder.add(ModItems.SMOKED_RICEBALL, "Smoked Riceball");
        translationBuilder.add(ModItems.SOAKED_WOOD, "Soaked Wood");
        translationBuilder.add(ModItems.SOAKED_WOODCHIP, "Soaked Woodchip");
        translationBuilder.add(ModItems.STABILIZED_CARBON, "Stabilized Carbon");
        translationBuilder.add(ModItems.STEEL, "Steel");
        translationBuilder.add(ModItems.STEEL_BOTTLE, "Steel Bottle");
        translationBuilder.add(ModItems.STEEL_JAR, "Steel Jar");
        translationBuilder.add(ModItems.STEEL_PART, "Steel Part");
        translationBuilder.add(ModItems.TARTPEPPER, "Tartpepper");
        translationBuilder.add("item.arknights_endfield.tartpepper", "Tartpepper");
        translationBuilder.add(ModItems.TARTPEPPER_PICKLE, "Tartpepper Pickle");
        translationBuilder.add(ModItems.TARTPEPPER_SALAD, "Tartpepper Salad");
        translationBuilder.add(ModItems.TARTPEPPER_SEED, "Tartpepper Seed");
        translationBuilder.add(ModItems.THORNY_YAZHEN, "Thorny Yazhen");
        translationBuilder.add("item.arknights_endfield.thorny_yazhen", "Thorny Yazhen");
        translationBuilder.add(ModItems.THORNY_YAZHEN_POWDER, "Thorny Yazhen Powder");
        translationBuilder.add(ModItems.UMBRALINE, "Umbraline");
        translationBuilder.add("item.arknights_endfield.umbraline", "Umbraline");
        translationBuilder.add(ModItems.VALLEY_GRAYBREAD, "Valley Graybread");
        translationBuilder.add(ModItems.WOOD, "Wood");
        translationBuilder.add(ModItems.WULING_FRIED_RICE, "Wuling Fried Rice");
        translationBuilder.add(ModItems.YAZHEN, "Yazhen");
        translationBuilder.add("item.arknights_endfield.yazhen", "Yazhen");
        translationBuilder.add(ModItems.YAZHEN_POWDER, "Yazhen Powder");
        translationBuilder.add(ModItems.YAZHEN_SEED, "Yazhen Seed");
        translationBuilder.add(ModItems.YAZHEN_SPRAY_L, "Yazhen Spray L");
        translationBuilder.add(ModItems.YAZHEN_SPRAY_S, "Yazhen Spray S");
        translationBuilder.add(ModItems.YAZHEN_SYRINGE_A, "Yazhen Syringe A");
        translationBuilder.add(ModItems.YAZHEN_SYRINGE_C, "Yazhen Syringe C");

        translationBuilder.add("blockEntity.portable_originium_rig", "Portable Originium Rig");
        translationBuilder.add("blockEntity.protocol_anchor_core", "Protocol Anchor Core");
        translationBuilder.add("blockEntity.thermal_bank", "Thermal Bank");
        translationBuilder.add("blockEntity.refining_unit", "Refining Unit");
        translationBuilder.add("blockEntity.gearing_unit", "Gearing Unit");
        translationBuilder.add("blockEntity.electric_mining_rig", "Electric Mining Rig");
        translationBuilder.add("blockEntity.electric_mining_rig_mk_ii", "Electric Mining Rig Mk II");
        translationBuilder.add("blockEntity.shredding_unit", "Shredding Unit");
        translationBuilder.add("blockEntity.fitting_unit", "Fitting Unit");
        translationBuilder.add("blockEntity.moulding_unit", "Moulding Unit");
        translationBuilder.add("blockEntity.planting_unit", "Planting Unit");
        translationBuilder.add("blockEntity.seed_picking_unit", "Seed-Picking Unit");
        translationBuilder.add("blockEntity.filling_unit", "Filling Unit");
        translationBuilder.add("blockEntity.grinding_unit", "Grinding Unit");
        translationBuilder.add("blockEntity.packaging_unit", "Packaging Unit");
        translationBuilder.add("blockEntity.crafter", "Crafter");

        translationBuilder.add("screen.protocol_core.buffer", "Stored:");
        translationBuilder.add("screen.protocol_core.storedEnergy", " %s /");
        translationBuilder.add("screen.protocol_core.max", "%s");
        translationBuilder.add("screen.protocol_core.generated", "Gen. %s");
        translationBuilder.add("screen.protocol_core.consumer", "%s Con.");
        translationBuilder.add("screen.protocol_core.load", "Load Node Num: %s");

        translationBuilder.add("itemGroup.arknights_endfield", "Arknights Endfield");
    }
}
