package com.besson.endfield.datagen;

import com.besson.endfield.block.ModBlocks;
import com.besson.endfield.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.client.BlockStateModelGenerator;
import net.minecraft.data.client.ItemModelGenerator;
import net.minecraft.data.client.Models;

public class ModModelsProvider extends FabricModelProvider {
    public ModModelsProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PROTOCOL_ANCHOR_CORE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.RELAY_TOWER);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ELECTRIC_PYLON);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ELECTRIC_MINING_RIG);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.ELECTRIC_MINING_RIG_MK_II);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PORTABLE_ORIGINIUM_RIG);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REFINING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SHREDDING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FILLING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FITTING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GEARING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GRINDING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MOULDING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PACKAGING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PLANTING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SEED_PICKING_UNIT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.THERMAL_BANK);

        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.REFINING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SHREDDING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FILLING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FITTING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GEARING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GRINDING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.MOULDING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PACKAGING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PLANTING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SEED_PICKING_UNIT_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.THERMAL_BANK_SIDE);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.FLUID_PUMP);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.PROTOCOL_ANCHOR_CORE_PORT);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.SUPPLY_TERMINAL);
        blockStateModelGenerator.registerNorthDefaultHorizontalRotation(ModBlocks.GUN_TOWER);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AMETHYST_ORE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CUPRIUM_ORE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_ORIGINIUM_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_FERRIUM_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_AMETHYST_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_CUPRIUM_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORIGINIUM_ORE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FERRIUM_ORE_BLOCK);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AMETHYST_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.COAL_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.COPPER_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CUPRIUM_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DIAMOND_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.EMERALD_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FERRIUM_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GOLD_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.IRON_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LAPIS_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORIGINIUM_MINERAL_VEIN_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.REDSTONE_MINERAL_VEIN_BLOCK);

        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CRAFTER);
    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(ModItems.AGGAGRIT, Models.GENERATED);
        itemModelGenerator.register(ModItems.AGGAGRIT_BLOCK, Models.GENERATED);
        itemModelGenerator.register(ModItems.AGGAGRIT_CLUSTER, Models.GENERATED);
        itemModelGenerator.register(ModItems.AKETINE, Models.GENERATED);
        itemModelGenerator.register(ModItems.AKETINE_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.AKETINE_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.AMBER_RICE, Models.GENERATED);
        itemModelGenerator.register(ModItems.AMBER_RICE_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.AMETHYST_BOTTLE, Models.GENERATED);
        itemModelGenerator.register(ModItems.AMETHYST_COMPONENT, Models.GENERATED);
        itemModelGenerator.register(ModItems.AMETHYST_FIBER, Models.GENERATED);
        itemModelGenerator.register(ModItems.AMETHYST_ORE, Models.GENERATED);
        itemModelGenerator.register(ModItems.AMETHYST_PART, Models.GENERATED);
        itemModelGenerator.register(ModItems.AMETHYST_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ARTS_TUBE, Models.GENERATED);
        itemModelGenerator.register(ModItems.ARTS_VIAL, Models.GENERATED);
        itemModelGenerator.register(ModItems.ASHPIN_REMEDY, Models.GENERATED);
        itemModelGenerator.register(ModItems.BIZARROTACK, Models.GENERATED);
        itemModelGenerator.register(ModItems.BIZARRO_CHILI, Models.GENERATED);
        itemModelGenerator.register(ModItems.BLANCHED_REMEDY, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCKFLOWER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCKFLOWER_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCKFLOWER_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCKPILL_L, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCKPILL_RF, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCKPILL_S, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCK_CAPSULE_A, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCK_CAPSULE_B, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUCK_CAPSULE_C, Models.GENERATED);
        itemModelGenerator.register(ModItems.BUGTACK, Models.GENERATED);
        itemModelGenerator.register(ModItems.CANNED_CITROME_A, Models.GENERATED);
        itemModelGenerator.register(ModItems.CANNED_CITROME_B, Models.GENERATED);
        itemModelGenerator.register(ModItems.CANNED_CITROME_C, Models.GENERATED);
        itemModelGenerator.register(ModItems.CARBON, Models.GENERATED);
        itemModelGenerator.register(ModItems.CARBON_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CARTILAGE_BIT, Models.GENERATED);
        itemModelGenerator.register(ModItems.CARTILAGE_TACK, Models.GENERATED);
        itemModelGenerator.register(ModItems.CHITIN_BIT, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROBUCKY_MIX, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROME, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROME_JAM, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROME_JELLY, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROME_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROME_PUDDING, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROME_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROMIX, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROMIX_L, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROMIX_RF, Models.GENERATED);
        itemModelGenerator.register(ModItems.CITROMIX_S, Models.GENERATED);
        itemModelGenerator.register(ModItems.COARSE_FLATBREAD, Models.GENERATED);
        itemModelGenerator.register(ModItems.CORRECTIVE_REMEDY, Models.GENERATED);
        itemModelGenerator.register(ModItems.CRYSTON_BOTTLE, Models.GENERATED);
        itemModelGenerator.register(ModItems.CRYSTON_COMPONENT, Models.GENERATED);
        itemModelGenerator.register(ModItems.CRYSTON_FIBER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CRYSTON_PART, Models.GENERATED);
        itemModelGenerator.register(ModItems.CRYSTON_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.CUPRIUM, Models.GENERATED);
        itemModelGenerator.register(ModItems.CUPRIUM_COMPONENT, Models.GENERATED);
        itemModelGenerator.register(ModItems.CUPRIUM_JAR, Models.GENERATED);
        itemModelGenerator.register(ModItems.CUPRIUM_ORE, Models.GENERATED);
        itemModelGenerator.register(ModItems.CUPRIUM_PART, Models.GENERATED);
        itemModelGenerator.register(ModItems.CUPRIUM_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.DENSE_CARBON_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.DENSE_FERRIUM_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.DENSE_ORIGINIUM_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.DENSE_ORIGOCRUST_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.FERRIUM, Models.GENERATED);
        itemModelGenerator.register(ModItems.FERRIUM_BOTTLE, Models.GENERATED);
        itemModelGenerator.register(ModItems.FERRIUM_COMPONENT, Models.GENERATED);
        itemModelGenerator.register(ModItems.FERRIUM_ORE, Models.GENERATED);
        itemModelGenerator.register(ModItems.FERRIUM_PART, Models.GENERATED);
        itemModelGenerator.register(ModItems.FERRIUM_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.FILLET, Models.GENERATED);
        itemModelGenerator.register(ModItems.FILLET_CONFIT, Models.GENERATED);
        itemModelGenerator.register(ModItems.FIREBUCKLE, Models.GENERATED);
        itemModelGenerator.register(ModItems.FIREBUCKLE_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.FIRESTOVE_RICE, Models.GENERATED);
        itemModelGenerator.register(ModItems.FIRETACK, Models.GENERATED);
        itemModelGenerator.register(ModItems.FLUFFED_JINCAO, Models.GENERATED);
        itemModelGenerator.register(ModItems.FLUFFED_JINCAO_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.FORTIFYING_INFUSION, Models.GENERATED);
        itemModelGenerator.register(ModItems.GARDEN_FRIED_RICE, Models.GENERATED);
        itemModelGenerator.register(ModItems.GARDEN_STIR_FRY, Models.GENERATED);
        itemModelGenerator.register(ModItems.GINSENG_MEAT_STEW, Models.GENERATED);
        itemModelGenerator.register(ModItems.GLOWBUG, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRASS_CHAFF, Models.GENERATED);
        itemModelGenerator.register(ModItems.GROUND_BUCKFLOWER_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GROUND_CITROME_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.HC_BATTERY, Models.GENERATED);
        itemModelGenerator.register(ModItems.HOLLOW_BONE, Models.GENERATED);
        itemModelGenerator.register(ModItems.HOLLOW_BONECHIP, Models.GENERATED);
        itemModelGenerator.register(ModItems.HOT_CRUNCHY_RIBS, Models.GENERATED);
        itemModelGenerator.register(ModItems.INDUSTRIAL_EXPLOSIVE, Models.GENERATED);
        itemModelGenerator.register(ModItems.JINCAO, Models.GENERATED);
        itemModelGenerator.register(ModItems.JINCAO_DRINK, Models.GENERATED);
        itemModelGenerator.register(ModItems.JINCAO_INFUSION, Models.GENERATED);
        itemModelGenerator.register(ModItems.JINCAO_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.JINCAO_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.JINCAO_TEA, Models.GENERATED);
        itemModelGenerator.register(ModItems.JINCAO_TISANE, Models.GENERATED);
        itemModelGenerator.register(ModItems.KUNST_TUBE, Models.GENERATED);
        itemModelGenerator.register(ModItems.KUNST_VIAL, Models.GENERATED);
        itemModelGenerator.register(ModItems.LC_BATTERY, Models.GENERATED);
        itemModelGenerator.register(ModItems.MEAT_STIR_FRY, Models.GENERATED);
        itemModelGenerator.register(ModItems.MOSSFIELD_PIE, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORIGINIUM_ORE, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORIGINIUM_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORIGOCRUST, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORIGOCRUST_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.PACKED_ORIGOCRUST, Models.GENERATED);
        itemModelGenerator.register(ModItems.PERPLEXING_MEDICATION, Models.GENERATED);
        itemModelGenerator.register(ModItems.PRESERVE_STEW, Models.GENERATED);
        itemModelGenerator.register(ModItems.REDJADE_GINSENG, Models.GENERATED);
        itemModelGenerator.register(ModItems.REDJADE_GINSENG_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.REED_RYE, Models.GENERATED);
        itemModelGenerator.register(ModItems.REED_RYE_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.SANDLEAF, Models.GENERATED);
        itemModelGenerator.register(ModItems.SANDLEAF_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.SANDLEAF_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAVORY_FILLET, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAVORY_TANGBAO, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAVORY_TANGMIAN, Models.GENERATED);
        itemModelGenerator.register(ModItems.SCORCHBUG, Models.GENERATED);
        itemModelGenerator.register(ModItems.SC_BATTERY, Models.GENERATED);
        itemModelGenerator.register(ModItems.SENSORY_REMEDY, Models.GENERATED);
        itemModelGenerator.register(ModItems.SMOKED_RICEBALL, Models.GENERATED);
        itemModelGenerator.register(ModItems.SOAKED_WOOD, Models.GENERATED);
        itemModelGenerator.register(ModItems.SOAKED_WOODCHIP, Models.GENERATED);
        itemModelGenerator.register(ModItems.STABILIZED_CARBON, Models.GENERATED);
        itemModelGenerator.register(ModItems.STEEL, Models.GENERATED);
        itemModelGenerator.register(ModItems.STEEL_BOTTLE, Models.GENERATED);
        itemModelGenerator.register(ModItems.STEEL_JAR, Models.GENERATED);
        itemModelGenerator.register(ModItems.STEEL_PART, Models.GENERATED);
        itemModelGenerator.register(ModItems.TARTPEPPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.TARTPEPPER_PICKLE, Models.GENERATED);
        itemModelGenerator.register(ModItems.TARTPEPPER_SALAD, Models.GENERATED);
        itemModelGenerator.register(ModItems.TARTPEPPER_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.THORNY_YAZHEN, Models.GENERATED);
        itemModelGenerator.register(ModItems.THORNY_YAZHEN_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.UMBRALINE, Models.GENERATED);
        itemModelGenerator.register(ModItems.VALLEY_GRAYBREAD, Models.GENERATED);
        itemModelGenerator.register(ModItems.WOOD, Models.GENERATED);
        itemModelGenerator.register(ModItems.WULING_FRIED_RICE, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAZHEN, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAZHEN_POWDER, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAZHEN_SEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAZHEN_SPRAY_L, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAZHEN_SPRAY_S, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAZHEN_SYRINGE_A, Models.GENERATED);
        itemModelGenerator.register(ModItems.YAZHEN_SYRINGE_C, Models.GENERATED);

    }
}
