package com.besson.endfield.datagen;

import com.besson.endfield.block.ModBlocks;
import com.besson.endfield.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;

public class ModZhCnLangProvider extends FabricLanguageProvider {
    public ModZhCnLangProvider(FabricDataOutput dataOutput) {
        super(dataOutput, "zh_cn");
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add(ModItems.PROTOCOL_ANCHOR_CORE_ITEM, "协议核心");
        translationBuilder.add(ModItems.RELAY_TOWER_ITEM, "中继器");
        translationBuilder.add(ModItems.ELECTRIC_PYLON_ITEM, "供电桩");
        translationBuilder.add(ModItems.ELECTRIC_MINING_RIG_ITEM, "电驱矿机");
        translationBuilder.add(ModItems.ELECTRIC_MINING_RIG_MK_II_ITEM, "二型电驱矿机");
        translationBuilder.add(ModItems.PORTABLE_ORIGINIUM_RIG_ITEM, "便携源石矿机");
        translationBuilder.add(ModItems.REFINING_UNIT_ITEM, "精炼炉");
        translationBuilder.add(ModItems.SHREDDING_UNIT_ITEM, "粉碎机");
        translationBuilder.add(ModItems.FILLING_UNIT_ITEM, "灌装机");
        translationBuilder.add(ModItems.FITTING_UNIT_ITEM, "配件机");
        translationBuilder.add(ModItems.GEARING_UNIT_ITEM, "装备原件机");
        translationBuilder.add(ModItems.GRINDING_UNIT_ITEM, "研磨机");
        translationBuilder.add(ModItems.MOULDING_UNIT_ITEM, "塑形机");
        translationBuilder.add(ModItems.PACKAGING_UNIT_ITEM, "封装机");
        translationBuilder.add(ModItems.PLANTING_UNIT_ITEM, "种植机");
        translationBuilder.add(ModItems.SEED_PICKING_UNIT_ITEM, "采种机");
        translationBuilder.add(ModItems.THERMAL_BANK_ITEM, "热能池");

        translationBuilder.add(ModBlocks.AMETHYST_MINERAL_VEIN_BLOCK, "紫水晶矿脉");
        translationBuilder.add(ModBlocks.COAL_MINERAL_VEIN_BLOCK, "煤矿脉");
        translationBuilder.add(ModBlocks.COPPER_MINERAL_VEIN_BLOCK, "铜矿脉");
        translationBuilder.add(ModBlocks.DIAMOND_MINERAL_VEIN_BLOCK, "钻石矿脉");
        translationBuilder.add(ModBlocks.EMERALD_MINERAL_VEIN_BLOCK, "绿宝石矿脉");
        translationBuilder.add(ModBlocks.GOLD_MINERAL_VEIN_BLOCK, "金矿脉");
        translationBuilder.add(ModBlocks.IRON_MINERAL_VEIN_BLOCK, "铁矿脉");
        translationBuilder.add(ModBlocks.LAPIS_MINERAL_VEIN_BLOCK, "青金石矿脉");
        translationBuilder.add(ModBlocks.ORIGINIUM_MINERAL_VEIN_BLOCK, "源石矿脉");
        translationBuilder.add(ModBlocks.REDSTONE_MINERAL_VEIN_BLOCK, "红石矿脉");
        translationBuilder.add(ModBlocks.AMETHYST_ORE_BLOCK, "紫水晶矿");
        translationBuilder.add(ModBlocks.CUPRIUM_MINERAL_VEIN_BLOCK, "赤铜矿脉");
        translationBuilder.add(ModBlocks.CUPRIUM_ORE_BLOCK, "赤铜矿");
        translationBuilder.add(ModBlocks.DEEPSLATE_AMETHYST_ORE, "深板岩紫水晶矿");
        translationBuilder.add(ModBlocks.DEEPSLATE_CUPRIUM_ORE, "深板岩赤铜矿");
        translationBuilder.add(ModBlocks.DEEPSLATE_FERRIUM_ORE, "深板岩蓝铁矿");
        translationBuilder.add(ModBlocks.DEEPSLATE_ORIGINIUM_ORE, "深板岩源石矿");
        translationBuilder.add(ModBlocks.FERRIUM_MINERAL_VEIN_BLOCK, "蓝铁矿脉");
        translationBuilder.add(ModBlocks.FERRIUM_ORE_BLOCK, "蓝铁矿");
        translationBuilder.add(ModBlocks.ORIGINIUM_ORE_BLOCK, "源石矿");

        translationBuilder.add(ModBlocks.CRAFTER, "制造台");

        translationBuilder.add(ModItems.AGGAGRIT, "异香石");
        translationBuilder.add(ModItems.AGGAGRIT_BLOCK, "异香石块");
        translationBuilder.add(ModItems.AGGAGRIT_CLUSTER, "异香石簇");
        translationBuilder.add(ModItems.AKETINE, "酮化灌木");
        translationBuilder.add("item.arknights_endfield.aketine", "酮化灌木");
        translationBuilder.add(ModItems.AKETINE_POWDER, "酮化灌木粉末");
        translationBuilder.add(ModItems.AKETINE_SEED, "酮化树种");
        translationBuilder.add(ModItems.AMBER_RICE, "Amber Rice");
        translationBuilder.add("item.arknights_endfield.amber_rice", "Amber Rice");
        translationBuilder.add(ModItems.AMBER_RICE_SEED, "Amber Rice Seed");
        translationBuilder.add(ModItems.AMETHYST_BOTTLE, "紫晶质瓶");
        translationBuilder.add(ModItems.AMETHYST_COMPONENT, "紫晶装备原件");
        translationBuilder.add(ModItems.AMETHYST_FIBER, "紫晶纤维");
        translationBuilder.add(ModItems.AMETHYST_ORE, "紫晶矿");
        translationBuilder.add(ModItems.AMETHYST_PART, "紫晶零件");
        translationBuilder.add(ModItems.AMETHYST_POWDER, "紫晶粉末");
        translationBuilder.add(ModItems.ARTS_TUBE, "Arts Tube");
        translationBuilder.add(ModItems.ARTS_VIAL, "刻术瓶");
        translationBuilder.add(ModItems.ASHPIN_REMEDY, "灰针秘剂");
        translationBuilder.add(ModItems.BIZARROTACK, "怪味饼干");
        translationBuilder.add(ModItems.BIZARRO_CHILI, "Bizarro Chili");
        translationBuilder.add(ModItems.BLANCHED_REMEDY, "苍白秘剂");
        translationBuilder.add(ModItems.BUCKFLOWER, "荞花");
        translationBuilder.add("item.arknights_endfield.buckflower", "荞花");
        translationBuilder.add(ModItems.BUCKFLOWER_POWDER, "荞花粉末");
        translationBuilder.add(ModItems.BUCKFLOWER_SEED, "荞花种子");
        translationBuilder.add(ModItems.BUCKPILL_L, "大瓶荞复锭剂");
        translationBuilder.add(ModItems.BUCKPILL_RF, "精选荞复锭剂");
        translationBuilder.add(ModItems.BUCKPILL_S, "小瓶荞复锭剂");
        translationBuilder.add(ModItems.BUCK_CAPSULE_A, "精选荞愈胶囊");
        translationBuilder.add(ModItems.BUCK_CAPSULE_B, "优质荞愈胶囊");
        translationBuilder.add(ModItems.BUCK_CAPSULE_C, "荞愈胶囊");
        translationBuilder.add(ModItems.BUGTACK, "虫粉饼干");
        translationBuilder.add(ModItems.CANNED_CITROME_A, "精选柑实罐头");
        translationBuilder.add(ModItems.CANNED_CITROME_B, "优质柑实罐头");
        translationBuilder.add(ModItems.CANNED_CITROME_C, "柑实罐头");
        translationBuilder.add(ModItems.CARBON, "碳块");
        translationBuilder.add(ModItems.CARBON_POWDER, "碳粉末");
        translationBuilder.add(ModItems.CARTILAGE_BIT, "软骨碎屑");
        translationBuilder.add(ModItems.CARTILAGE_TACK, "软骨饼干");
        translationBuilder.add(ModItems.CHITIN_BIT, "虫壳碎屑");
        translationBuilder.add(ModItems.CITROBUCKY_MIX, "荞柑混剂");
        translationBuilder.add(ModItems.CITROME, "柑实");
        translationBuilder.add("item.arknights_endfield.citrome", "柑实");
        translationBuilder.add(ModItems.CITROME_JAM, "柑橘风味果酱");
        translationBuilder.add(ModItems.CITROME_JELLY, "柑实风味果冻");
        translationBuilder.add(ModItems.CITROME_POWDER, "柑实粉末");
        translationBuilder.add(ModItems.CITROME_PUDDING, "瓶装柑橘布丁");
        translationBuilder.add(ModItems.CITROME_SEED, "柑实种子");
        translationBuilder.add(ModItems.CITROMIX, "柑实冲剂");
        translationBuilder.add(ModItems.CITROMIX_L, "Citromix L");
        translationBuilder.add(ModItems.CITROMIX_RF, "Citromix Rf");
        translationBuilder.add(ModItems.CITROMIX_S, "Citromix S");
        translationBuilder.add(ModItems.COARSE_FLATBREAD, "粗制麦饼");
        translationBuilder.add(ModItems.CORRECTIVE_REMEDY, "Corrective Remedy");
        translationBuilder.add(ModItems.CRYSTON_BOTTLE, "高晶质瓶");
        translationBuilder.add(ModItems.CRYSTON_COMPONENT, "高晶装备原件");
        translationBuilder.add(ModItems.CRYSTON_FIBER, "高晶纤维");
        translationBuilder.add(ModItems.CRYSTON_PART, "高晶零件");
        translationBuilder.add(ModItems.CRYSTON_POWDER, "高晶粉末");
        translationBuilder.add(ModItems.CUPRIUM, "赤铜块");
        translationBuilder.add(ModItems.CUPRIUM_COMPONENT, "赤铜装备原件");
        translationBuilder.add(ModItems.CUPRIUM_JAR, "赤铜罐");
        translationBuilder.add(ModItems.CUPRIUM_ORE, "赤铜矿");
        translationBuilder.add(ModItems.CUPRIUM_PART, "铜制零件");
        translationBuilder.add(ModItems.CUPRIUM_POWDER, "赤铜粉末");
        translationBuilder.add(ModItems.DENSE_CARBON_POWDER, "致密碳粉末");
        translationBuilder.add(ModItems.DENSE_FERRIUM_POWDER, "致密蓝铁粉末");
        translationBuilder.add(ModItems.DENSE_ORIGINIUM_POWDER, "致密源石粉末");
        translationBuilder.add(ModItems.DENSE_ORIGOCRUST_POWDER, "致密晶体粉末");
        translationBuilder.add(ModItems.FERRIUM, "蓝铁块");
        translationBuilder.add(ModItems.FERRIUM_BOTTLE, "蓝铁瓶");
        translationBuilder.add(ModItems.FERRIUM_COMPONENT, "蓝铁装备原件");
        translationBuilder.add(ModItems.FERRIUM_ORE, "蓝铁矿");
        translationBuilder.add(ModItems.FERRIUM_PART, "铁质零件");
        translationBuilder.add(ModItems.FERRIUM_POWDER, "蓝铁粉末");
        translationBuilder.add(ModItems.FILLET, "兽肉");
        translationBuilder.add(ModItems.FILLET_CONFIT, "油封赤盐焗兽排");
        translationBuilder.add(ModItems.FIREBUCKLE, "映火荞花");
        translationBuilder.add("item.arknights_endfield.firebuckle", "映火荞花");
        translationBuilder.add(ModItems.FIREBUCKLE_POWDER, "荞愈粉末");
        translationBuilder.add(ModItems.FIRESTOVE_RICE, "Firestove Rice");
        translationBuilder.add(ModItems.FIRETACK, "Firetack");
        translationBuilder.add(ModItems.FLUFFED_JINCAO, "蓬茸锦草");
        translationBuilder.add("item.arknights_endfield.fluffed_jincao", "蓬茸锦草");
        translationBuilder.add(ModItems.FLUFFED_JINCAO_POWDER, "蓬茸锦草粉末");
        translationBuilder.add(ModItems.FORTIFYING_INFUSION, "正本补元汤剂");
        translationBuilder.add(ModItems.GARDEN_FRIED_RICE, "Garden Fried Rice");
        translationBuilder.add(ModItems.GARDEN_STIR_FRY, "炝炒时蔬");
        translationBuilder.add(ModItems.GINSENG_MEAT_STEW, "Ginseng Meat Stew");
        translationBuilder.add(ModItems.GLOWBUG, "萤壳虫");
        translationBuilder.add(ModItems.GRASS_CHAFF, "草籽碎屑");
        translationBuilder.add(ModItems.GROUND_BUCKFLOWER_POWDER, "细磨荞花粉末");
        translationBuilder.add(ModItems.GROUND_CITROME_POWDER, "细末柑实粉末");
        translationBuilder.add(ModItems.HC_BATTERY, "高容电池");
        translationBuilder.add(ModItems.HOLLOW_BONE, "中空骨块");
        translationBuilder.add(ModItems.HOLLOW_BONECHIP, "中空骨片");
        translationBuilder.add(ModItems.HOT_CRUNCHY_RIBS, "重辣烤脆骨");
        translationBuilder.add(ModItems.INDUSTRIAL_EXPLOSIVE, "工业爆炸物");
        translationBuilder.add(ModItems.JINCAO, "锦草");
        translationBuilder.add("item.arknights_endfield.jincao", "锦草");
        translationBuilder.add(ModItems.JINCAO_DRINK, "锦草软饮");
        translationBuilder.add(ModItems.JINCAO_INFUSION, "Jincao Infusion");
        translationBuilder.add(ModItems.JINCAO_POWDER, "锦草粉末");
        translationBuilder.add(ModItems.JINCAO_SEED, "锦草种子");
        translationBuilder.add(ModItems.JINCAO_TEA, "优质锦草软饮");
        translationBuilder.add(ModItems.JINCAO_TISANE, "锦草 Tisane");
        translationBuilder.add(ModItems.KUNST_TUBE, "附术铁瓶");
        translationBuilder.add(ModItems.KUNST_VIAL, "附术瓶");
        translationBuilder.add(ModItems.LC_BATTERY, "低容电池");
        translationBuilder.add(ModItems.MEAT_STIR_FRY, "Meat Stir Fry");
        translationBuilder.add(ModItems.MOSSFIELD_PIE, "Mossfield Pie");
        translationBuilder.add(ModItems.ORIGINIUM_ORE, "源矿");
        translationBuilder.add(ModItems.ORIGINIUM_POWDER, "源石粉末");
        translationBuilder.add(ModItems.ORIGOCRUST, "晶体外壳");
        translationBuilder.add(ModItems.ORIGOCRUST_POWDER, "晶体外壳粉末");
        translationBuilder.add(ModItems.PACKED_ORIGOCRUST, "密制晶体");
        translationBuilder.add(ModItems.PERPLEXING_MEDICATION, "意乱药剂");
        translationBuilder.add(ModItems.PRESERVE_STEW, "干菜羹");
        translationBuilder.add(ModItems.REDJADE_GINSENG, "琼叶参");
        translationBuilder.add("item.arknights_endfield.redjade_ginseng", "琼叶参");
        translationBuilder.add(ModItems.REDJADE_GINSENG_SEED, "琼叶参种子");
        translationBuilder.add(ModItems.REED_RYE, "灰芦麦");
        translationBuilder.add("item.arknights_endfield.reed_rye", "灰芦麦");
        translationBuilder.add(ModItems.REED_RYE_SEED, "灰芦麦种子");
        translationBuilder.add(ModItems.SANDLEAF, "砂叶");
        translationBuilder.add("item.arknights_endfield.sandleaf", "砂叶");
        translationBuilder.add(ModItems.SANDLEAF_POWDER, "砂叶粉末");
        translationBuilder.add(ModItems.SANDLEAF_SEED, "砂叶种子");
        translationBuilder.add(ModItems.SAVORY_FILLET, "异香兽排");
        translationBuilder.add(ModItems.SAVORY_TANGBAO, "异香汤包");
        translationBuilder.add(ModItems.SAVORY_TANGMIAN, "异香汤面");
        translationBuilder.add(ModItems.SCORCHBUG, "灼壳虫");
        translationBuilder.add(ModItems.SC_BATTERY, "中容电池");
        translationBuilder.add(ModItems.SENSORY_REMEDY, "Sensory Remedy");
        translationBuilder.add(ModItems.SMOKED_RICEBALL, "Smoked Riceball");
        translationBuilder.add(ModItems.SOAKED_WOOD, "浸水木块");
        translationBuilder.add(ModItems.SOAKED_WOODCHIP, "浸水木片");
        translationBuilder.add(ModItems.STABILIZED_CARBON, "稳定碳块");
        translationBuilder.add(ModItems.STEEL, "钢块");
        translationBuilder.add(ModItems.STEEL_BOTTLE, "钢质瓶");
        translationBuilder.add(ModItems.STEEL_JAR, "钢质罐");
        translationBuilder.add(ModItems.STEEL_PART, "钢质零件");
        translationBuilder.add(ModItems.TARTPEPPER, "苦叶椒");
        translationBuilder.add("item.arknights_endfield.tartpepper", "苦叶椒");
        translationBuilder.add(ModItems.TARTPEPPER_PICKLE, "苦叶椒腌菜");
        translationBuilder.add(ModItems.TARTPEPPER_SALAD, "苦叶沙拉");
        translationBuilder.add(ModItems.TARTPEPPER_SEED, "苦叶椒种子");
        translationBuilder.add(ModItems.THORNY_YAZHEN, "荆刺芽针");
        translationBuilder.add("item.arknights_endfield.thorny_yazhen", "荆刺芽针");
        translationBuilder.add(ModItems.THORNY_YAZHEN_POWDER, "荆刺芽针粉末");
        translationBuilder.add(ModItems.UMBRALINE, "Umbraline");
        translationBuilder.add("item.arknights_endfield.umbraline", "黯银柑实");
        translationBuilder.add(ModItems.VALLEY_GRAYBREAD, "Valley Graybread");
        translationBuilder.add(ModItems.WOOD, "原木");
        translationBuilder.add(ModItems.WULING_FRIED_RICE, "Wuling Fried Rice");
        translationBuilder.add(ModItems.YAZHEN, "芽针");
        translationBuilder.add("item.arknights_endfield.yazhen", "芽针");
        translationBuilder.add(ModItems.YAZHEN_POWDER, "芽针粉末");
        translationBuilder.add(ModItems.YAZHEN_SEED, "芽针种子");
        translationBuilder.add(ModItems.YAZHEN_SPRAY_L, "Yazhen Spray L");
        translationBuilder.add(ModItems.YAZHEN_SPRAY_S, "Yazhen Spray S");
        translationBuilder.add(ModItems.YAZHEN_SYRINGE_A, "优质芽针针剂");
        translationBuilder.add(ModItems.YAZHEN_SYRINGE_C, "芽针针剂");

        translationBuilder.add("blockEntity.portable_originium_rig", "便携源石矿机");
        translationBuilder.add("blockEntity.protocol_anchor_core", "协议核心");
        translationBuilder.add("blockEntity.thermal_bank", "热能池");
        translationBuilder.add("blockEntity.refining_unit", "精炼炉");
        translationBuilder.add("blockEntity.gearing_unit", "装备原件机");
        translationBuilder.add("blockEntity.electric_mining_rig", "电驱矿机");
        translationBuilder.add("blockEntity.electric_mining_rig_mk_ii", "二型电驱矿机");
        translationBuilder.add("blockEntity.shredding_unit", "粉碎机");
        translationBuilder.add("blockEntity.fitting_unit", "配件机");
        translationBuilder.add("blockEntity.moulding_unit", "塑形机");
        translationBuilder.add("blockEntity.planting_unit", "种植机");
        translationBuilder.add("blockEntity.seed_picking_unit", "采种机");
        translationBuilder.add("blockEntity.filling_unit", "灌装机");
        translationBuilder.add("blockEntity.grinding_unit", "研磨机");
        translationBuilder.add("blockEntity.packaging_unit", "封装机");
        translationBuilder.add("blockEntity.crafter", "制造台");

        translationBuilder.add("screen.protocol_core.buffer", "电池储能:");
        translationBuilder.add("screen.protocol_core.storedEnergy", " %s /");
        translationBuilder.add("screen.protocol_core.max", "%s");
        translationBuilder.add("screen.protocol_core.generated", "发电功率 %s");
        translationBuilder.add("screen.protocol_core.consumer", "%s 用电功率");

        translationBuilder.add("itemGroup.arknights_endfield", "明日方舟：终末地" );
    }
}
